services:
  db:
    image: postgres:16-alpine
    container_name: gamefestival_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamefest
      POSTGRES_PASSWORD: gamefest
      POSTGRES_DB: gamefest 
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamefest"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s


  adminer:
    image: adminer
    container_name: gamefestival_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db


  nginx:
    image: nginx:alpine
    container_name: gamefestival_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gamefestival_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://gamefest:gamefest@db:5432/gamefest
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npm run dev"


  importer:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gamefestival_importer
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://gamefest:gamefest@db:5432/gamefest
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install --silent && npx prisma generate && npx prisma db push --accept-data-loss && npx ts-node ./scripts/import-csv.ts && npx ts-node ./scripts/seed-test-data.ts"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gamefestival_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      API_URL: https://162.38.111.36/api
    depends_on:
      - backend

volumes:
  db_data: